sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ibX8nrMDeZN5UU9fYS+lIBRWUuRh3L0ihDNr5sM4txRrxJ8yx5d/Ed7ZKCzl6pNeXd8zUFYJ36Wlyfy0ontrjMBWbwMi1D8j+qhEn9+YJ4y5CUPKKUvrdWgjnay6TmmcMGr5GVdIurbfXAQe6iqCpC5NBaMBzi5JOxELohv4E1+MIQ+Fup6mGe9Z0Jmj3W8k4d7GzpQ23pBZ3ZeWo0joOUz8SgJlf/jYG3OC5JOhxHaE9Hb4KOgbgLYeG8W4bXAx9zVaMlyuqxrWV3LRRzhbJaTH3VywcbkmA0SHfRgePqL0MwwAi3UyQZW1XuuhA0yLjjNy/4AT3EA3X2HUhtTII3BEgKrdhBJ6r4MD1hQ15cLxvm9RBw/czvMaK51Fnb1h4I8bA4Af/9Cnda10bTycqJyi5DMqNMm0Fefg2KOoTNhLsEZbeyqmj4gbZ1HGnbNbKBKV0okoIT+YxxJ8ODYULps1QkwL278TvrX4HeqYWjji/1mbAQYv/4TJEKACpDwrCJ690nw1K9881H1ijY51VqT+u+mjP5XnucXfanzTprmeEvMGyAte8ipq/v8CujcLCIzGKUnT1iTGpmQP7auqY3Gog1nTZ5K5RkX/KuovSBVxF4FwsHpbL3qqq+LyLMvavg7xfZgHjPNBVdsmmyETHxotVWR7HeR0vjfx2OwdVrw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Cast-Upon-the-Breakers_399
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy